### ISSUE TITLE
Cannot compile tutorial01.ml

### ISSUE THREAD

**Issue by thanhtoantnt** [chifflier/ocaml-llvm-tutorial#1]
I follow your first tutorial but got this message when I ran make
- ocaml version: 4.02.1
- llvm version: 3.5
# 

ocamlbuild -classic-display -j 0 -cflags -w,@a-4 -use-ocamlfind -pkgs llvm,llvm.bitreader  -I src -build-dir build/tutorial1 tutorial1.byte
ocamlfind ocamldep -package llvm.bitreader -package llvm -modules src/tutorial1.ml > src/tutorial1.ml.depends
ocamlfind ocamlc -c -w @a-4 -package llvm.bitreader -package llvm -I src -o src/tutorial1.cmo src/tutorial1.ml
- ocamlfind ocamlc -c -w @a-4 -package llvm.bitreader -package llvm -I src -o src/tutorial1.cmo src/tutorial1.ml
  File "src/tutorial1.ml", line 1:
  Error: /usr/lib/ocaml/llvm-3.5/./llvm.cmi
  is not a compiled interface for this version of OCaml.
  It seems to be for an older version of OCaml.
  Command exited with code 2.
  Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.
  
  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:
  
  ```
  true: -traverse
  <dir1> or <dir2>: traverse
  ```
  #

**Comment by chifflier** [comment]
> is not a compiled interface for this version of OCaml.
> It seems to be for an older version of OCaml.

This seems to be the problem: all OCaml modules have to be compiled using the same version of compiler.
I think the compiler you are using to build the tutorial is not the same that was used for the bindings.
